# These are supported funding model platforms
  
github: [relequestual]  )rnames e. c[user1, user2]  
patreon: # Replace with a single Patreon username
open_collective: json-schema
ko_fi: relequestual
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/standard
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://buymeacoffee.com/relequestual
